$DomainSuffix = 'domain.local'
$vCenterServer = 'vcenter server'
$SubnetMask = 'mask'
$DefaultGateway = 'gateway'
$DNS01 = 'dns01'
$DNS02 = 'dns02'
$OSCusSpec = 'OS Custom Spec Template Name'     
$Template = 'VM Template Name'
$ProdVMConvention = "ABCProd*"
$DevVMConvention = "ABCDev*"
$ProdCluster = "Production"
$DevCluster = "Development"
$ProdFolder = "Prod"
$DevFolder = "Dev"
$ProdStorage = 'prodsan*'
$DevStorage = 'devsan*'
